# Generated by Django 5.0.7 on 2024-09-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_wikiimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='wiki_images/'),
        ),
        migrations.DeleteModel(
            name='WikiImage',
        ),
    ]
