# Generated by Django 5.0.7 on 2024-09-21 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_wikipage_images_delete_wikiimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='images',
        ),
        migrations.CreateModel(
            name='WikiImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wiki_images/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='entries.wikipage')),
            ],
        ),
    ]
