# Generated by Django 5.0.7 on 2024-09-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_remove_wikipage_images_wikiimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WikiImages',
            new_name='WikiImage',
        ),
    ]
