# Generated by Django 5.0.7 on 2024-09-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_wikipage_image_delete_wikiimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wiki_images/')),
                ('wiki_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entries.wikipage')),
            ],
        ),
    ]
